### Get all projects
GET http://localhost:5034/api/Project/
###

GET http://localhost:5034/api/Task/1

### Create a new project
POST http://localhost:5034/api/Project
Content-Type: application/json

{
  
  "name": "Test Project",
  "description": "This is an example project.",
  "user_id": 1
}

### Create a new project
POST http://localhost:5034/api/Task
Content-Type: application/json

{
  "title":"sda",
	"description": "NewDescript",
	"State": false,
	"project_id": 1
}

### Create a new project
PATCH  http://localhost:5034/api/Task/1
Content-Type: application/json

{
	"State": true
}
###

DELETE  http://localhost:5034/api/Task/1
###
DELETE  http://localhost:5034/api/Project/1
